from envs.settings.vectors import attribute_paths, NODE_TYPES
ARTIST_VECTOR_SIZE = 18
AVG_VECTOR_SIZE = len(attribute_paths)
POSITION_NODE_TYPE_SIZE = len(NODE_TYPES)
RADAR_COUNTS_SIZE  = 4
MAX_OBJECTS = 5 
MAX_ARTIST = 3

ARTIST_INFO_SIZE = MAX_ARTIST * 4

REL_POS_SIZE = MAX_OBJECTS * 3


START_RADAR = ARTIST_VECTOR_SIZE + AVG_VECTOR_SIZE + POSITION_NODE_TYPE_SIZE
END_RADAR = START_RADAR + RADAR_COUNTS_SIZE
START_REL_POS = END_RADAR
END_REL_POS = START_REL_POS + REL_POS_SIZE
START_ARTIST_INFO = END_REL_POS
END_ARTIST_INFO = START_ARTIST_INFO + ARTIST_INFO_SIZE